name: update

on:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: "master"

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: update README
      env:
        GITHUB_USER: "d-tsuji"
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go run main.go
        git config user.name "${GITHUB_USER}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git commit -am "Auto update"
        git push -u origin master
