name: update

on:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Update README
      env:
        GITHUB_USER: "d-tsuji"
        GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go run main.go
        git config user.name "${GITHUB_USER}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git commit -am "auto update"
        git push -u origin master
